### ISSUE TITLE
Cannot Change Href, Affecting SEO

### ISSUE THREAD

**Issue by 1991Pawel** [jonelantha/react-responsive-pagination#105]
Currently, it is not possible to change the href, and this negatively impacts SEO.

`href={linkHref === 'hash' ? '#' : undefined}`

**Comment by jonelantha** [comment]
Thank you for your request 😄 

I'll implement this by allowing the linkHref prop to be a callback, here's an example:

```jsx
<ResponsivePagination
  ...
  linkHref={page => `/content/${page}`}
/>
```

This should give full flexibility in case there is any logic based on the page number

**Comment by jonelantha** [comment]
v2.8.0 supports a callback value for `linkHref`

Please see https://react-responsive-pagination.elantha.com/props/#misc-props for an example

Thank you for your request 😄

**Comment by 1991Pawel** [comment]
Thank you for implementing this feature so quickly.
