### ISSUE TITLE
UseLayoutEffect Warning

### ISSUE THREAD

**Issue by FluxusGaming** [jonelantha/react-responsive-pagination#36]
Warning: **useLayoutEffect** does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
at BootstrapPagination

I hope it can be solved, it is a very good library!

**Comment by jonelantha** [comment]
Thanks 😄

Yes, good point, built-in support for SSR is something I'm hoping to add

Until then, here's a workaround I'm currently using - only rendering the component on the client:

```jsx
function App(props) {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    ...
       {isClient && <Pagination ... />}
    ...
  );
}
```
Not perfect but it avoids the warning at least. Better SSR should be coming soon 😄
