### ISSUE TITLE
markup for active page link

### ISSUE THREAD

**Issue by sKopheK** [jonelantha/react-responsive-pagination#60]
hi, v1.8.1
why automatically hide label/number of the active page (actually setting `aria-hidden` attribute)? how does user get notification about current page number?

`<a class="page-link" href="#" aria-label="(current)"><span aria-hidden="true">1</span><span class="sr-only">(current)</span></a>`

is there a way how to turn this behavior off? setting `ariaCurrentAttr` prop should be sufficient

**Comment by jonelantha** [comment]
Hi

Yes you are right, this is incorrect, the page number should not be hidden. I will change fix that

Until then, if you use props of `ariaCurrentAttr='page' a11yActiveLabel=''` then you get this html for the current page link, which may be acceptable:

```html
<li class="page-item active" aria-current="page">
  <a class="page-link" href="#">9</a>
</li>
```

(this will probably become the default in V2)
This should give the correct aria labels and not turn off the number
