### ISSUE TITLE
wrong buttons for next/previous page

### ISSUE THREAD

**Issue by jopke** [jonelantha/react-responsive-pagination#7]
The buttons presented for next and previous page are actually meant for first/last page. It would be nice to render both :)

Also (separate issue, really), the ellipsis should be clickable.

**Comment by jopke** [comment]
FYI I am basing this off of my experience with the ultimate-pagination project.

**Comment by jonelantha** [comment]
Thank you for your comments.
Enhancements are planned for the buttons - I'll try and investigate if these changes can be incorporated.
