### ISSUE TITLE
nav classNames, ellipsis onClick

### ISSUE THREAD

**Issue by brokuka** [jonelantha/react-responsive-pagination#70]
Dear contributers, add support nav classNames and onClick ellipsis. Using last version of library this is not.

**Comment by jonelantha** [comment]
Thank you for your suggestions 😄 
Adding classNames to the nav elements is a great idea which will be included in a release soon.

Please can you let me know what clicking on the ellipsis would do?
Would it be the same as clicking the next/previous nav? Or something else?

**Comment by jonelantha** [comment]
v2.1 includes props for nav button classes
Please reopen this issue (or create a new issue) when you're able to let me know more about clicking on the ellipsis 😄
