### ISSUE TITLE
How to set previous and next arrow in fully right and left align 

### ISSUE THREAD

**Issue by pratiweb** [jonelantha/react-responsive-pagination#80]
Want to change structure of paginate links because want to set design like bellow. Need different div structure for previous an next 
![paginate](https://github.com/jonelantha/react-responsive-pagination/assets/37148199/4b963b01-4a93-44ba-a9bc-fcaddf9ab8dd)

**Comment by jonelantha** [comment]
Hi
I'll investigate what the options are to solve this, but it may not be possible with the current version

**Comment by jonelantha** [comment]
Thanks for your request 😄 this should now be possible, please see https://react-responsive-pagination.elantha.com/custom-styled-pagination/#justifying-previous--next-buttons
