### ISSUE TITLE
[Question] How I can set lest number when render on SP?

### ISSUE THREAD

**Issue by ngoclammevn** [jonelantha/react-responsive-pagination#81]
## This is my case
![image](https://github.com/jonelantha/react-responsive-pagination/assets/76934994/779b68f0-5cb3-4ad1-810c-6477c67c2440)
## My expected
I just want to show:
[<<] [...] [ 3 ][ 4 ][ 5 ][...][>>]
How can I configure it?

**Comment by jonelantha** [comment]
I'll add support for this in the next release

Until then please see https://react-responsive-pagination.elantha.com/props/#narrowBehaviour in case any of those are helpful

**Comment by jonelantha** [comment]
Try using
```js
import { dropFirstAndLast } from 'react-responsive-pagination/narrowBehaviour';
....
<Pagination
         ...
          narrowBehaviour={dropFirstAndLast}
/>
```

You can also combine with dropEllipsis:

```js
import { dropFirstAndLast, dropEllipsis, combine } from 'react-responsive-pagination/narrowBehaviour';
....
<Pagination
         ...
          narrowBehaviour={combine(dropFirstAndLast, dropEllipsis)}
/>
```

See https://react-responsive-pagination.elantha.com/props/#misc-props
