### ISSUE TITLE
Label as component.

### ISSUE THREAD

**Issue by pioner-rtx** [jonelantha/react-responsive-pagination#84]
Hi. Is it possible add ability for adding in label any components for customizing it. Currently I added it, but TS highlight an error and pagination buttons have broken styles with paddings because images have display:block

<ResponsivePagination
          current={currentPage || 0}
          total={totalPages}
          onPageChange={onChangePage}
          className="flex justify-end bg-white rounded-[10px]"
          pageLinkClassName=' py-2 px-4  font-semibold'
          pageItemClassName='border border-r-0 border-[#E9EEF3] py-2 mr-[-1px] text-[#1573FF]'
          activeItemClassName='relative border-r-[1px] border-[#1573FF] bg-[#1573FF] text-white z-10'
          previousClassName='rounded-l-[10px] font-semibold border-[#E9EEF3]'
          nextClassName='rounded-r-[10px] font-medium border-r-[1px] border-[#E9EEF3]'
          //@ts-ignore
          previousLabel={<ArrowLeftIcon />}
          //@ts-ignore
          nextLabel={<ArrowRightIcon />}
 />

With display:block
<img width="919" alt="Снимок экрана 2023-12-01 в 14 47 37" src="https://github.com/jonelantha/react-responsive-pagination/assets/124098391/e32e4eab-d4c5-47e4-9186-32da26883b60">

without display:block
<img width="844" alt="Снимок экрана 2023-12-01 в 14 47 25" src="https://github.com/jonelantha/react-responsive-pagination/assets/124098391/1185254b-bfaa-4645-a364-c4d7ce72234b">

**Comment by jonelantha** [comment]
Hopefully a future planned version will allow full rendering control over each element but at the moment it's text only. It may be possible to relax this to allow elements as labels, I'll investigate what would be involved for this and why it's not presently working.
